# Output
output_dir: output

# Model init kwargs
model_init_kwargs:
  attn_implementation: eager
  torch_dtype: float32

# Training arguments
max_steps: 2000
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5e-7
lr_scheduler_type: cosine
# lr_scheduler_kwargs:
#   min_lr: 2.0e-7
warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001
max_completion_length: 1024
num_generations: 8
pad_to_multiple_of: 512

# vllm arguments
# vllm model impl: transformers
use_vllm: true
vllm_mode: colocate 
vllm_importance_sampling_correction: true
vllm_importance_sampling_mode: "sequence_mask"
vllm_importance_sampling_cap: 3.0

# vllm_server_host: 0.0.0.0
# vllm_server_port: 8000
# vllm_group_port: 51216

# Logging arguments
logging_strategy: steps
logging_steps: 10
report_to: ["tensorboard"]
  # report_to: []
save_strategy: "steps"
save_steps: 10000
seed: 42

